### ISSUE TITLE
Is there a way to use custom word lists?

### ISSUE THREAD

**Issue by HatScripts** [LuminosoInsight/wordfreq#52]
Is there a way to use custom word lists? Say if I wanted to know the frequency of the word "whale" in the text of Moby Dick. I would have thought such a task would be within the scope of this library, yet I can't find anything in the documentation about it.

I realise that I could use the `tokenize` method combined with something like `collections.Counter`, but that would seem to somewhat defeat the purpose.

I've tried the following but to no avail:
```py
with Path("moby_dick.txt").open() as f:
    moby_dick = f.read()
    tokenized = tokenize(moby_dick, "en")
    whale_freq = word_frequency("whale", "en", wordlist=tokenized)
    print("whale_freq:", whale_freq)
```
```py
with Path("moby_dick.txt").open() as f:
    moby_dick = f.read()
    whale_freq = word_frequency("whale", "en", wordlist=moby_dick)
    print("whale_freq:", whale_freq)
```

**Comment by rspeer** [comment]
I think you *should* use `tokenize` combined with `collections.Counter`. That's essentially what we do in the first place in the package that generates these word lists, https://github.com/LuminosoInsight/exquisite-corpus. `wordfreq` is just for making the results easily available.
