### ISSUE TITLE
Regex version is incompatible with spaCy

### ISSUE THREAD

**Issue by jlpeck** [LuminosoInsight/wordfreq#63]
I'm interested in using wordfreq in a project I'm doing with spaCy; unfortunately, both wordfreq and spaCy require different versions of regex at an exact version number. Would it be possible to loosen the requirements on the regex version needed?

**Comment by rspeer** [comment]
Makes sense to me.

I wish that regex could provide more meaningful version numbers about what breaks compatibility. Anyway, from looking at the changelog, I believe that any version from 2017-07-11 to 2018-02-20 _should_ have the same behavior in wordfreq.

A problem still remains when I want to upgrade past the breaking changes in segmentation on 2018-06-05 and 2018-06-08.

**Comment by rspeer** [comment]
Fixed in version 2.2.1, which is out now.
