### ISSUE TITLE
Suggestion: allow function for `minimum`

### ISSUE THREAD

**Issue by gezakerecsenyi** [LuminosoInsight/wordfreq#72]
I am very grateful for the current `minimum` argument: it has helped me on many occasions. However, I am wondering if it would be possible for `minimum` to also accept a function/`lamda`, since this would simplify a lot of things? For instance, something like:

```
zipf_frequency("dog", "en", minimum=lambda word: math.log10(len(word)))
```

**Comment by rspeer** [comment]
Thanks for the suggestion. But it appears to me that this could be done in a shorter, simpler way with no extra code needed in wordfreq:

```
max(zipf_frequency("dog", "en"), math.log10(len(word)))
```
