### ISSUE TITLE
Upload 2.4 and 2.4.1 to PyPI

### ISSUE THREAD

**Issue by frankier** [LuminosoInsight/wordfreq#90]
Hi! I noticed you've added versions 2.4 and 2.4.1 to the changelog:

https://github.com/LuminosoInsight/wordfreq/blob/master/CHANGELOG.md

But not to PyPI

https://pypi.org/project/wordfreq/#history

Would it be possible to uploade them to PyPI?

**Comment by rspeer** [comment]
Thanks for letting me know - I don't have a good repeatable release process. I've caught up and released and tagged v2.4.1 and v2.4.2. (I don't see much point to going back and releasing v2.4.0, as 2.4.1 is so similar.)
